name: Build Pico Launcher release

on:
  release:
    types: [published]
  workflow_dispatch:
  
jobs:
  pico_launcher:
    runs-on: ubuntu-latest
    container: skylyrac/blocksds:slim-v1.16.0
    name: Build Pico Launcher
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          submodules: true
      - name: Install zip
        run:
          apt-get update && apt-get -y install zip
      - name: Run build script
        run: |
          make
      - name: Publish build to GH Actions
        uses: actions/upload-artifact@v4
        with:
          path: |
            _pico/
            LAUNCHER.nds
          name: Pico_Launcher
      - name: Add safe directory exception
        run: git config --global --add safe.directory /__w/the-homebrew-unlauncher/the-homebrew-unlauncher
      - name: Package for release
        run: |
          mkdir Homebrew_Unlauncher
          cp -r _pico/ LAUNCHER.nds Homebrew_Unlauncher
          cd Homebrew_Unlauncher && zip -r $PWD.zip *
          git tag v1.1.0
          git push origin v1.1.0
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            Homebrew_Unlauncher.zip
